export enum Relationship {
  MOTHER = 'MOTHER',
  FATHER = 'FATHER',
  GRANDMOTHER = 'GRANDMOTHER',
  GRANDFATHER = 'GRANDFATHER',
  AUNT = 'AUNT',
  UNCLE = 'UNCLE',
  GODMOTHER = 'GODMOTHER',
  GODFATHER = 'GODFATHER',
  OTHER = 'OTHER'
}