export enum Relationship {
  SON = 'SON',
  DAUGHTER = 'DAUGHTER',
  NIECE = 'NIECE',
  NEPHEW = 'NEPHEW',
  SISTER = 'SISTER',
  BROTHER = 'BROTHER',
  GODSON = 'GODSON',
  GODDAUGHTER = 'GODDAUGHTER',
  GRANDSON = 'GRANDSON',
  GRANDDAUGHTER = 'GRANDDAUGHTER',
  OTHER = 'OTHER'
}